- web/public/script.js
- web/views/index.hbs
> feat: ページネーション実装

- .github/workflows/docker-multi.yml
- web/src/app.controller.ts
- web/views/index.hbs
> feat: package.jsonにバージョンを入れるように

- web/public/script.js
- web/views/index.hbs
> feat: 表示するターゲットを変更できるように

- crawler/src/crawler.ts
- crawler/src/entities/mutes.ts
- crawler/src/mysql.ts
> feat: ミュートサポート

- .github/workflows/docker-multi.yml
- web/Dockerfile
- web/package.json
- web/src/components/CardItem.vue
- web/yarn.lock
> feat: デザインの修正

- web/src/components/TargetSelector.vue
> feat: 2秒以内にターゲットセレクターの変更が行われた場合は遅延させる

- crawler/src/entities/tweets.ts
- crawler/src/main.ts
- crawler/src/migration.ts
- crawler/src/mysql.ts
- web/nuxt.config.ts
- web/package.json
- web/src/app.vue
- web/src/components/TagSelector.vue
- web/src/types/types.ts
> feat: タグ検索機能の実装

- web/src/app.vue
- web/src/components/DarkModeSwitch.vue
- web/src/components/GlobalSnackbar.vue
- web/src/components/TheHeader.vue
- web/src/store/settings.ts
- web/src/store/snackbar.ts
- close #105 
特にスマホUIは全然納得がいってないのでプルリク求む
あとボタンのスタイルは私の力では実装できなかった（丸っこくして真ん中でぶった斬るの、CSSでどう表現するんだ…）
| Device | Before | After |
| :- | :-: | :-: |
| PC | ![image](https://user-images.githubusercontent.com/8929706/208517136-82137c7b-267d-4c5b-bf4b-0056e579469c.png) | ![image](https://user-images.githubusercontent.com/8929706/208517122-1e95e801-a8b2-46dc-a665-90cf0c3e66fe.png) |
| iPhone SE | ![image](https://user-images.githubusercontent.com/8929706/208517456-e7d250eb-f45b-4557-9a51-e581a2b120c0.png) | ![image](https://user-images.githubusercontent.com/8929706/208517491-1f88525a-d1fd-40eb-b3a4-7433df5d0091.png) |
| iPad Air | ![image](https://user-images.githubusercontent.com/8929706/208517696-8f185de2-652a-401b-a48b-1e7be2945b85.png) | …
> feat: ヘッダー部分の再構成

- web/package.json
- web/yarn.lock
Downgrade vue-tsc v1.0.13
- [johnsoncodehk/volar#2227](https://togithub.com/johnsoncodehk/volar/issues/2227)
> fix: vue-tsc v1.0.13

- web/src/components/CardItem.vue
- web/src/components/DarkModeSwitch.vue
- web/src/components/TagSelector.vue
- web/src/components/TargetSelector.vue
- web/src/components/TheHeader.vue
- 携帯でも表示が崩れないようにしました
- ヘッダー部分の余白を統一しました
- 画像部分でカーソルがポインターに変わるようにしました
> feat: mobile responsive design

- crawler/package.json
- crawler/src/config.ts
- crawler/src/endpoints/twitter-router.ts
- crawler/src/server.ts
- crawler/yarn.lock
- web/src/app.vue
- web/src/components/CardItem.vue
- web/src/components/TheHeader.vue
- web/src/store/twitter.ts
- Twitterへログインできるように
- ツイートをWebアプリ上からいいねできるように
以下の設定項目を追加
```yaml
twitter:
auth:
appKey: Twitterキー
appSecret: Twitterシークレットキー
callbackUrl: コールバックURL
session:
secret: 32文字以上のシークレットキー
isSecure: HTTPS環境かどうかのboolean値
```
> feat: Twitterとの連携機能実装

- web/src/components/CardItem.vue
・getCardTitleClassの数値の調整
・likeボタンを画像の上に配置
> feat: UIの改善

- web/src/app.vue
- web/src/components/CardItem.vue
- web/src/components/DarkModeSwitch.vue
- web/src/components/GlobalSnackbar.vue
- web/src/components/ItemWrapper.vue
- web/src/components/MagicGrid.vue
- web/src/components/TagSelector.vue
- web/src/components/TargetSelector.vue
- web/src/components/TheHeader.vue
- web/src/store/settings.ts
- web/src/store/snackbar.ts
- web/src/store/twitter.ts
- web/src/store/viewed.ts
> feat: jsdocを書いた

- web/src/app.vue
- web/src/components/CardItem.vue
- web/src/components/TheHeader.vue
- web/src/store/twitter.ts
> feat: エラー処理の改善、削除済み画像の場合にその旨を表示する

- .github/workflows/add-reviewer.yml
> ci: レビュアー追加処理をgithub-scriptに移動

- crawler/src/discord.ts
- crawler/src/twitter.ts
> fix: like関連のエラー修正

- crawler/src/discord.ts
- crawler/src/twitter.ts
> fix: tweetIdが丸められてツイートが削除扱いになる問題の修正

- crawler/src/discord.ts
- close https://github.com/tomacheese/watch-twitter-likes/issues/386
> feat: 完全失敗した場合はDMにエラーを投げる

- crawler/package.json
- crawler/src/generate-type-interface.ts
- crawler/src/main.ts
- crawler/yarn.lock
> feat: 型定義生成モードの追加

- crawler/package.json
- crawler/yarn.lock
> feat: twittertsアップデート
